# Generated by Django 2.0.5 on 2021-11-11 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookno', models.IntegerField(db_column='BookNo', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('author', models.CharField(blank=True, db_column='Author', max_length=50, null=True)),
                ('issuedate', models.CharField(blank=True, db_column='IssueDate', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=60, null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('issuedate', models.CharField(blank=True, db_column='IssueDate', max_length=60, null=True)),
                ('bookno', models.ForeignKey(blank=True, db_column='BookNo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.Books')),
            ],
        ),
    ]
